### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [hhc97/flatliner-src#3]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by hhc97** [comment]
Hi, thank you for your suggestion, I'll look into this when I have some time!

**Comment by hhc97** [comment]
Hi, thank you again for the tip here, I ended up adding an MIT license with a note that contributions back to source will be appreciated :)

**Comment by TechnologyClassroom** [comment]
Without the legal requirement to share source with users, most organizations turn MIT licensed code into proprietary software without notifying upstream projects that they depend on. Though MIT is still an improvement from before. Thank you!

**Comment by hhc97** [comment]
That's a fair point. For this particular project however, I'm ok with that because there's (in my opinion) not much potential for any commercial application. I'm happy if anyone wants to use it at all!
